# Generated by Django 3.1.7 on 2021-03-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='Post_Subject',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='Summary',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
